const LISTINGS = [
  {
    id: 1,
    address: "18256 21A Avenue",
    area: "Hazelmere, Surrey",
    price: "$8,500,000",
    sqft: 12364,
    tags: ["ACREAGE"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1069740/web/18256-21a-avenue-hazelmere-south-surrey-white-rock-01.jpg?timestamp=1780352660",
    beds: 7, baths: 8, fullBaths: 6, halfBaths: 2,
    mls: "R2987401", type: "House", lotSize: "43,560 sqft", frontage: "165.00 ft",
    taxes: "$22,400.00", parking: "Garage Triple, Additional Parking", view: "Valley and mountain",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2019, style: "Contemporary",
    pricePerSqft: "$688",
    description: "An extraordinary estate-sized property in the coveted Hazelmere community. This magnificent residence sits on over an acre of beautifully landscaped grounds and features a grand open-concept layout with soaring ceilings, chef's kitchen, home theatre, wine cellar, and a resort-style backyard with pool and cabana. The finest craftsmanship and materials throughout."
  },
  {
    id: 2,
    address: "15730 38A Avenue",
    area: "Morgan Creek, Surrey",
    price: "$2,699,000",
    sqft: 4600,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1068227/web/15730-38a-avenue-morgan-creek-south-surrey-white-rock-01.jpg?timestamp=1779823645",
    beds: 5, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3012845", type: "House", lotSize: "9,800 sqft", frontage: "72.00 ft",
    taxes: "$9,850.00", parking: "Garage Double", view: "Garden",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2015, style: "Traditional",
    pricePerSqft: "$587",
    description: "Stunning home in the prestigious Morgan Creek community. Featuring a gourmet kitchen with high-end appliances, spacious living areas, and a beautifully landscaped backyard perfect for entertaining. Close to Morgan Creek Golf Course and top-rated schools."
  },
  {
    id: 3,
    address: "15963 Devonshire Drive",
    area: "Morgan Creek, Surrey",
    price: "$2,868,000",
    sqft: 5828,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1067890/web/15963-devonshire-drive-morgan-creek-south-surrey-white-rock-01.jpg?timestamp=1779741180",
    beds: 6, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3018766", type: "House", lotSize: "11,200 sqft", frontage: "82.00 ft",
    taxes: "$10,200.00", parking: "Garage Double, Additional Parking", view: "Garden and park",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2017, style: "Traditional",
    pricePerSqft: "$492",
    description: "Elegant family home in sought-after Morgan Creek. Grand foyer entrance, formal living and dining rooms, gourmet kitchen with wok room, media room, and a beautifully appointed master suite. Professionally landscaped yard with covered patio."
  },
  {
    id: 4,
    address: "5-15688 28 Avenue",
    area: "Grandview Surrey",
    price: "$1,130,000",
    sqft: 2212,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1064029/web/15688-28-avenue-grandview-surrey-south-surrey-white-rock-01.jpg?timestamp=1778271968",
    beds: 3, baths: 3, fullBaths: 2, halfBaths: 1,
    mls: "R3024510", type: "Townhouse", lotSize: "2,100 sqft", frontage: "N/A",
    taxes: "$4,200.00", parking: "Garage Double", view: "Garden",
    basement: "None", storeys: 3, yearBuilt: 2020, style: "Contemporary",
    pricePerSqft: "$511",
    description: "Modern townhome in Grandview Surrey. Open-concept main floor, chef's kitchen with quartz counters, rooftop patio, and double garage. Walking distance to shopping, restaurants, and transit."
  },
  {
    id: 5,
    address: "16428 28 Avenue",
    area: "Grandview Surrey",
    price: "$2,999,000",
    sqft: 5036,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1062905/web/16428-28-avenue-grandview-surrey-south-surrey-white-rock-01.jpg?timestamp=1778011869",
    beds: 6, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3031204", type: "House", lotSize: "8,500 sqft", frontage: "68.00 ft",
    taxes: "$9,100.00", parking: "Garage Triple", view: "Mountain",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2021, style: "Contemporary",
    pricePerSqft: "$596",
    description: "Luxurious custom-built home in Grandview Surrey. Features include a grand open layout, gourmet kitchen, spice kitchen, theatre room, wet bar, and a meticulously landscaped backyard with mountain views."
  },
  {
    id: 6,
    address: "13666 30 Avenue",
    area: "Elgin Chantrell, Surrey",
    price: "$2,499,000",
    sqft: 3506,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1062504/web/13666-30-avenue-elgin-chantrell-south-surrey-white-rock-01.jpg?timestamp=1777925462",
    beds: 4, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R3027890", type: "House", lotSize: "14,800 sqft", frontage: "98.00 ft",
    taxes: "$8,750.00", parking: "Garage Double", view: "Garden",
    basement: "Crawl Space", storeys: 2, yearBuilt: 2008, style: "Craftsman",
    pricePerSqft: "$713",
    description: "Beautifully maintained home in the exclusive Elgin Chantrell neighbourhood. Set on a large private lot with mature trees, this home features a warm and inviting interior, updated kitchen, and a spacious backyard with room for a pool."
  },
  {
    id: 7,
    address: "3122 136 Street",
    area: "Elgin Chantrell, Surrey",
    price: "$6,488,888",
    sqft: 8169,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1062491/web/3122-136-street-elgin-chantrell-south-surrey-white-rock-01.jpg?timestamp=1777925462",
    beds: 7, baths: 8, fullBaths: 6, halfBaths: 2,
    mls: "R3041122", type: "House", lotSize: "28,700 sqft", frontage: "148.00 ft",
    taxes: "$18,600.00", parking: "Garage Triple, Additional Parking", view: "Garden and trees",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2018, style: "Contemporary",
    pricePerSqft: "$794",
    description: "A rare estate in one of South Surrey's most prestigious enclaves. This architectural masterpiece spans over 8,000 sqft on a sprawling 28,700 sqft lot. Grand entertaining spaces, home automation, indoor pool, and every luxury imaginable."
  },
  {
    id: 8,
    address: "3852 156A Street",
    area: "Morgan Creek, Surrey",
    price: "$2,595,000",
    sqft: 4278,
    tags: ["MOUNTAIN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1062490/web/3852-156a-street-morgan-creek-south-surrey-white-rock-01.jpg?timestamp=1777925462",
    beds: 5, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3045677", type: "House", lotSize: "9,100 sqft", frontage: "70.00 ft",
    taxes: "$9,450.00", parking: "Garage Double", view: "Mountain",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2016, style: "Traditional",
    pricePerSqft: "$607",
    description: "Stunning Morgan Creek home with panoramic mountain views. Boasting an open great room, gourmet kitchen, main floor master retreat, and a beautifully appointed lower level with media room and guest suite."
  },
  {
    id: 9,
    address: "1266 Everall Street",
    area: "White Rock",
    price: "$3,698,000",
    sqft: 5155,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1060539/web/1266-everall-street-white-rock-south-surrey-white-rock-01.jpg?timestamp=1777320684",
    beds: 5, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3052910", type: "House", lotSize: "7,200 sqft", frontage: "60.00 ft",
    taxes: "$12,100.00", parking: "Garage Double, Open", view: "Ocean and mountain",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2020, style: "Contemporary",
    pricePerSqft: "$717",
    description: "Breathtaking ocean views from this stunning White Rock contemporary. Every principal room captures sweeping views of Semiahmoo Bay. Features include a chef's kitchen, main floor master, rooftop deck, and suite potential."
  },
  {
    id: 10,
    address: "2737 Crescent Drive",
    area: "Crescent Beach / Ocean Park",
    price: "$5,150,000",
    sqft: 8221,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1060325/web/2737-crescent-drive-crescent-bch-ocean-pk-south-surrey-white-rock-01.jpg?timestamp=1777075980",
    beds: 6, baths: 7, fullBaths: 6, halfBaths: 1,
    mls: "R3058430", type: "House", lotSize: "22,000 sqft", frontage: "130.00 ft",
    taxes: "$15,800.00", parking: "Garage Triple", view: "Garden and park",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2017, style: "Traditional",
    pricePerSqft: "$626",
    description: "Magnificent estate in the coveted Crescent Beach enclave. This grand residence sits on a beautifully landscaped lot and features soaring ceilings, a grand foyer, formal entertaining spaces, and a resort-style backyard."
  },
  {
    id: 11,
    address: "13169 Marine Drive",
    area: "Crescent Beach / Ocean Park",
    price: "$3,480,000",
    sqft: 5000,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1059753/web/13169-marine-drive-crescent-bch-ocean-pk-south-surrey-white-rock-01.jpg?timestamp=1776903134",
    beds: 5, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R3061900", type: "House", lotSize: "10,500 sqft", frontage: "80.00 ft",
    taxes: "$11,200.00", parking: "Garage Double, Open", view: "Ocean and Gulf Islands",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2014, style: "West Coast Contemporary",
    pricePerSqft: "$696",
    description: "Perched above Marine Drive with sweeping ocean and Gulf Island views. This West Coast contemporary home features floor-to-ceiling windows, open living spaces that flow to a stunning view deck, and a master suite with spa ensuite."
  },
  {
    id: 12,
    address: "2141 179 Street",
    area: "Hazelmere, Surrey",
    price: "$2,695,000",
    sqft: 3067,
    tags: ["ACREAGE"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1059364/web/2141-179-street-hazelmere-south-surrey-white-rock-01.jpg?timestamp=1776816727",
    beds: 4, baths: 3, fullBaths: 3, halfBaths: 0,
    mls: "R3066120", type: "House", lotSize: "87,120 sqft", frontage: "220.00 ft",
    taxes: "$8,900.00", parking: "Garage Double, Additional Parking", view: "Pastoral and mountain",
    basement: "Crawl Space", storeys: 1, yearBuilt: 2005, style: "Rancher",
    pricePerSqft: "$879",
    description: "Rare two-acre acreage property in Hazelmere. This well-maintained rancher sits in complete privacy, surrounded by mature trees and open fields. A wonderful opportunity for those seeking land with a quality home in a serene setting."
  },
  {
    id: 13,
    address: "15957 39A Avenue",
    area: "Morgan Creek, Surrey",
    price: "$3,650,000",
    sqft: 6640,
    tags: ["MOUNTAIN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1057812/web/15957-39a-avenue-morgan-creek-south-surrey-white-rock-01.jpg?timestamp=1776292318",
    beds: 6, baths: 6, fullBaths: 5, halfBaths: 1,
    mls: "R3070455", type: "House", lotSize: "13,200 sqft", frontage: "92.00 ft",
    taxes: "$12,700.00", parking: "Garage Triple", view: "Mountain and golf course",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2019, style: "Contemporary",
    pricePerSqft: "$550",
    description: "Exceptional Morgan Creek estate with sweeping mountain and golf course views. This custom-built masterpiece features an open great room, chef's kitchen with wok room, home theatre, wine cellar, and an outdoor kitchen and pool."
  },
  {
    id: 14,
    address: "1360 Everall Street",
    area: "White Rock",
    price: "$1,475,000",
    sqft: 1450,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1056766/web/1360-everall-street-white-rock-south-surrey-white-rock-01.jpg?timestamp=1776111123",
    beds: 2, baths: 2, fullBaths: 2, halfBaths: 0,
    mls: "R3074800", type: "Condo", lotSize: "N/A", frontage: "N/A",
    taxes: "$4,900.00", parking: "Underground Single", view: "Ocean, panoramic",
    basement: "None", storeys: 1, yearBuilt: 2022, style: "High-Rise",
    pricePerSqft: "$1,017",
    description: "Stunning ocean-view residence in one of White Rock's most coveted buildings. Floor-to-ceiling windows frame spectacular views of Semiahmoo Bay. Features include a gourmet kitchen, spa-like ensuite, and a generous view terrace."
  },
  {
    id: 15,
    address: "2620 139A Street",
    area: "Elgin Chantrell, Surrey",
    price: "$2,388,000",
    sqft: 4330,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1055458/web/2620-139a-street-elgin-chantrell-south-surrey-white-rock-01.jpg?timestamp=1775680285",
    beds: 5, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R3079210", type: "House", lotSize: "15,600 sqft", frontage: "104.00 ft",
    taxes: "$8,400.00", parking: "Garage Double", view: "Garden",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2006, style: "Traditional",
    pricePerSqft: "$552",
    description: "Classic Elgin Chantrell home on a beautifully private lot. Featuring formal living and dining rooms, a large family room, updated kitchen, and a peaceful backyard retreat. Ideally located near Chantrell Creek Elementary."
  },
  {
    id: 16,
    address: "3472 164A Street",
    area: "Morgan Creek, Surrey",
    price: "$4,895,000",
    sqft: 10367,
    tags: ["MOUNTAIN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1054181/web/3472-164a-street-morgan-creek-south-surrey-white-rock-01.jpg?timestamp=1775160790",
    beds: 7, baths: 8, fullBaths: 7, halfBaths: 1,
    mls: "R3083600", type: "House", lotSize: "20,100 sqft", frontage: "125.00 ft",
    taxes: "$16,200.00", parking: "Garage Quad", view: "Mountain panoramic",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2021, style: "Contemporary",
    pricePerSqft: "$472",
    description: "Ultra-luxury Morgan Creek estate with jaw-dropping mountain panoramas. This architecturally designed masterpiece spans over 10,000 sqft and features every conceivable luxury — from the grand foyer and floating staircase to the indoor pool and home automation system."
  },
  {
    id: 17,
    address: "13464 13A Avenue",
    area: "Crescent Beach / Ocean Park",
    price: "$7,580,000",
    sqft: 6821,
    tags: ["WATERFRONT"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1054153/web/13464-13a-avenue-crescent-bch-ocean-pk-south-surrey-white-rock-01.jpg?timestamp=1775160790",
    beds: 6, baths: 7, fullBaths: 6, halfBaths: 1,
    mls: "R3088945", type: "House", lotSize: "18,300 sqft", frontage: "110.00 ft",
    taxes: "$21,400.00", parking: "Garage Triple, Additional Parking", view: "Ocean, waterfront",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2016, style: "West Coast Contemporary",
    pricePerSqft: "$1,111",
    description: "Absolute waterfront perfection in Crescent Beach. This stunning West Coast contemporary sits directly on the water and offers unobstructed panoramic ocean views from every room. Private dock, seawall access, and resort-style outdoor living."
  },
  {
    id: 18,
    address: "16730 26 Avenue",
    area: "Grandview Surrey",
    price: "$1,435,000",
    sqft: 2332,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1053312/web/16730-26-avenue-grandview-surrey-south-surrey-white-rock-01.jpg?timestamp=1774979013",
    beds: 3, baths: 3, fullBaths: 2, halfBaths: 1,
    mls: "R3090100", type: "Townhouse", lotSize: "2,800 sqft", frontage: "N/A",
    taxes: "$4,700.00", parking: "Garage Double", view: "Garden",
    basement: "None", storeys: 3, yearBuilt: 2021, style: "Contemporary",
    pricePerSqft: "$615",
    description: "Beautifully finished townhome in Grandview Surrey. Features an open main floor with 9ft ceilings, chef's kitchen, and a private rooftop patio. Close to amenities, parks, and top-rated schools."
  },
  {
    id: 19,
    address: "16625 Bell Road",
    area: "Cloverdale, Surrey",
    price: "$2,399,000",
    sqft: 4888,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1049916/web/16625-bell-road-road-cloverdale-bc-cloverdale-01.jpg?timestamp=1773697392",
    beds: 5, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3091780", type: "House", lotSize: "9,600 sqft", frontage: "74.00 ft",
    taxes: "$8,300.00", parking: "Garage Double, Additional Parking", view: "Garden",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2013, style: "Traditional",
    pricePerSqft: "$491",
    description: "Spacious family home in desirable Cloverdale. This well-appointed residence features a grand open floor plan, chef's kitchen with large island, main floor den, and a fully finished basement with media room and guest suite."
  },
  {
    id: 20,
    address: "16768 26 Avenue",
    area: "Grandview Surrey",
    price: "$3,180,000",
    sqft: 2184,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1049152/web/16768-26-avenue-grandview-surrey-south-surrey-white-rock-01.jpg?timestamp=1773259903",
    beds: 3, baths: 2, fullBaths: 2, halfBaths: 0,
    mls: "R3094500", type: "House", lotSize: "6,400 sqft", frontage: "52.00 ft",
    taxes: "$7,200.00", parking: "Garage Double", view: "None",
    basement: "None", storeys: 1, yearBuilt: 2023, style: "Rancher",
    pricePerSqft: "$1,456",
    description: "Brand new luxury rancher in Grandview Surrey. Everything on one level with wide plank hardwood, vaulted ceilings, a chef's kitchen, spa master ensuite, and a beautiful private yard. Perfect for downsizers seeking quality and convenience."
  },
  {
    id: 21,
    address: "14878 Buena Vista Avenue",
    area: "White Rock",
    price: "$1,468,000",
    sqft: 2400,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1047419/web/14878-buena-vista-avenue-white-rock-south-surrey-white-rock-01.jpg?timestamp=1772659899",
    beds: 3, baths: 3, fullBaths: 2, halfBaths: 1,
    mls: "R3096740", type: "House", lotSize: "5,000 sqft", frontage: "50.00 ft",
    taxes: "$5,800.00", parking: "Garage Single, Open", view: "Ocean",
    basement: "Partial", storeys: 2, yearBuilt: 1995, style: "Traditional",
    pricePerSqft: "$612",
    description: "Lovely White Rock home with ocean glimpses. Enjoy peek-a-boo views of Semiahmoo Bay from the upper level. Updated kitchen and bathrooms, hardwood floors, and a charming backyard garden. Steps to the beach promenade."
  },
  {
    id: 22,
    address: "16211 29 Avenue",
    area: "Grandview Surrey",
    price: "$4,498,000",
    sqft: 6788,
    tags: ["ACREAGE"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1044522/web/16211-29-avenue-grandview-surrey-south-surrey-white-rock-02.jpg?timestamp=1771536379",
    beds: 6, baths: 7, fullBaths: 6, halfBaths: 1,
    mls: "R3098120", type: "House", lotSize: "43,560 sqft", frontage: "180.00 ft",
    taxes: "$14,900.00", parking: "Garage Triple, Additional Parking", view: "Pastoral",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2018, style: "Contemporary",
    pricePerSqft: "$663",
    description: "Exceptional one-acre estate in Grandview Surrey. This custom home commands a beautifully manicured acre lot with a private gated entrance. Grand proportions throughout, including a chef's kitchen, wine cellar, home gym, and resort-style backyard."
  },
  {
    id: 23,
    address: "14534 Lombard Place",
    area: "Sullivan Station, Surrey",
    price: "$2,449,000",
    sqft: 3462,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1043388/web/14534-lombard-place-sullivan-station-surrey-01.jpg?timestamp=1771031543",
    beds: 4, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R3089420", type: "House", lotSize: "25,403 sqft", frontage: "102.00 ft",
    taxes: "$9,001.76", parking: "Additional Parking, Garage Double, Open, Front A", view: "Southern valley and water",
    basement: "Full, Finished", storeys: 2, yearBuilt: 1973, style: "Rancher/Bungalow w/Bsmt.",
    pricePerSqft: "$707",
    description: "Estate-sized property in Sullivan Station with rare southern valley and water views. This lovingly maintained home sits on over 25,000 sqft of land and offers incredible development potential or the perfect canvas for a custom renovation."
  },
  {
    id: 24,
    address: "14237 Vine Avenue",
    area: "White Rock",
    price: "$2,795,000",
    sqft: 5018,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1036855/web/14237-vine-avenue-white-rock-south-surrey-white-rock-01.jpg?timestamp=1768877325",
    beds: 5, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3101800", type: "House", lotSize: "8,100 sqft", frontage: "62.00 ft",
    taxes: "$10,200.00", parking: "Garage Double", view: "Garden",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2012, style: "Traditional",
    pricePerSqft: "$557",
    description: "Beautifully appointed White Rock home on a quiet street. Featuring a grand open plan, gourmet kitchen, formal dining, and a fully finished basement with in-law suite. Walk to White Rock beach, restaurants, and boutique shops."
  },
  {
    id: 25,
    address: "PH 2 - 1501 Foster Street",
    area: "White Rock",
    price: "$5,950,000",
    sqft: 3798,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1035230/web/1501-foster-street-white-rock-south-surrey-white-rock-01.jpg?timestamp=1768065458",
    beds: 3, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R3104400", type: "Penthouse", lotSize: "N/A", frontage: "N/A",
    taxes: "$16,800.00", parking: "Underground Double", view: "Ocean, panoramic 180°",
    basement: "None", storeys: 1, yearBuilt: 2023, style: "Ultra-Luxury Penthouse",
    pricePerSqft: "$1,566",
    description: "The pinnacle of White Rock luxury living. This full-floor penthouse commands 180-degree panoramic ocean views from every room. Featuring a private rooftop terrace, chef's kitchen with top-of-the-line appliances, and bespoke finishes throughout."
  },
  {
    id: 26,
    address: "PH801 - 1551 Foster Street",
    area: "White Rock",
    price: "$2,998,800",
    sqft: 5191,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1032651/web/1551-foster-street-white-rock-south-surrey-white-rock-01.jpg?timestamp=1765848488",
    beds: 3, baths: 3, fullBaths: 3, halfBaths: 0,
    mls: "R3107200", type: "Penthouse", lotSize: "N/A", frontage: "N/A",
    taxes: "$10,400.00", parking: "Underground Triple", view: "Ocean panoramic",
    basement: "None", storeys: 1, yearBuilt: 2022, style: "Luxury Penthouse",
    pricePerSqft: "$578",
    description: "Spectacular ocean-view penthouse in White Rock's most sought-after address. Expansive open living areas with floor-to-ceiling windows, a chef's kitchen, three spa-like suites, and multiple terraces to soak in the endless ocean vistas."
  },
  {
    id: 27,
    address: "3222 137A Street",
    area: "Elgin Chantrell, Surrey",
    price: "$2,880,000",
    sqft: 3365,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1015235/web/3222-137a-street-elgin-chantrell-south-surrey-white-rock-01.jpg?timestamp=1757973093",
    beds: 4, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R3110500", type: "House", lotSize: "17,200 sqft", frontage: "108.00 ft",
    taxes: "$9,500.00", parking: "Garage Double", view: "Garden and trees",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2009, style: "Traditional",
    pricePerSqft: "$856",
    description: "Charming Elgin Chantrell home on a large private lot surrounded by mature trees. Featuring a warm and inviting interior, updated kitchen and bathrooms, and a beautiful backyard perfect for the family. Close to Crescent Beach Elementary."
  },
  {
    id: 28,
    address: "14448 Blackburn Crescent",
    area: "White Rock",
    price: "$5,280,000",
    sqft: 5961,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/985899/web/14448-blackburn-crescent-white-rock-south-surrey-white-rock-01.jpg?timestamp=1747343665",
    beds: 5, baths: 6, fullBaths: 5, halfBaths: 1,
    mls: "R3113800", type: "House", lotSize: "9,600 sqft", frontage: "70.00 ft",
    taxes: "$16,200.00", parking: "Garage Double, Additional", view: "Ocean, panoramic",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2021, style: "Contemporary",
    pricePerSqft: "$885",
    description: "One of White Rock's finest ocean-view estates. Custom built to the highest standards with panoramic views from all principal rooms. Features include a chef's and catering kitchen, home theatre, gym, and a stunning outdoor living area with ocean views."
  },
  {
    id: 29,
    address: "14659 West Beach Avenue",
    area: "White Rock",
    price: "$1,950,000",
    sqft: 2363,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/975297/web/14659-west-beach-avenue-white-rock-south-surrey-white-rock-01.jpg?timestamp=1744146126",
    beds: 3, baths: 2, fullBaths: 2, halfBaths: 0,
    mls: "R3117100", type: "House", lotSize: "4,800 sqft", frontage: "40.00 ft",
    taxes: "$6,400.00", parking: "Open", view: "Ocean direct",
    basement: "None", storeys: 2, yearBuilt: 2000, style: "West Coast",
    pricePerSqft: "$825",
    description: "Steps to the beach with spectacular direct ocean views. This West Coast home features an open main floor with stunning views, wraparound deck, and is ideally located on one of White Rock's most coveted beachside streets."
  },
  {
    id: 30,
    address: "13832 32 Avenue",
    area: "Elgin Chantrell, Surrey",
    price: "$7,980,000",
    sqft: 8088,
    tags: ["ACREAGE"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/973096/web/13832-32-avenue-elgin-chantrell-south-surrey-white-rock-01.jpg?timestamp=1743555821",
    beds: 7, baths: 8, fullBaths: 6, halfBaths: 2,
    mls: "R3120400", type: "House", lotSize: "43,560 sqft", frontage: "200.00 ft",
    taxes: "$22,800.00", parking: "Garage Quad, Additional Parking", view: "Garden, pastoral",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2020, style: "Contemporary",
    pricePerSqft: "$987",
    description: "An unparalleled Elgin Chantrell estate on a full acre of manicured grounds. This architectural gem blends modern luxury with timeless elegance. Grand 7-bedroom layout, home automation, wine cellar, home theatre, and a resort-calibre backyard."
  },
  {
    id: 31,
    address: "13021 Crescent Road",
    area: "Elgin Chantrell, Surrey",
    price: "$3,998,000",
    sqft: 2079,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/966801/web/13021-crescent-road-elgin-chantrell-south-surrey-white-rock-01.jpg?timestamp=1741374995",
    beds: 3, baths: 2, fullBaths: 2, halfBaths: 0,
    mls: "R3123700", type: "House", lotSize: "18,900 sqft", frontage: "110.00 ft",
    taxes: "$11,600.00", parking: "Garage Double, Additional", view: "Ocean and Gulf Islands",
    basement: "Partial", storeys: 1, yearBuilt: 1975, style: "Rancher",
    pricePerSqft: "$1,923",
    description: "Rare ocean-view property on prestigious Crescent Road with sweeping views of the Gulf Islands and Semiahmoo Bay. Offered as a land value opportunity on a nearly 19,000 sqft lot — build your dream ocean-view estate in one of Surrey's most coveted addresses."
  },
  {
    id: 32,
    address: "414 - 1526 Finlay Street",
    area: "White Rock",
    price: "$1,199,900",
    sqft: 1373,
    tags: [],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/966629/web/1526-finlay-street-white-rock-south-surrey-white-rock-01.jpg?timestamp=1741312783",
    beds: 2, baths: 2, fullBaths: 2, halfBaths: 0,
    mls: "R3126900", type: "Condo", lotSize: "N/A", frontage: "N/A",
    taxes: "$3,800.00", parking: "Underground Single", view: "City and garden",
    basement: "None", storeys: 1, yearBuilt: 2018, style: "Mid-Rise",
    pricePerSqft: "$874",
    description: "Elegant condo in the heart of White Rock. Featuring a gourmet kitchen, open living spaces, and a large balcony. Walk to everything — boutique shops, restaurants, and the beautiful White Rock promenade and beach."
  },
  {
    id: 33,
    address: "1259 Everall Street",
    area: "White Rock",
    price: "$2,050,000",
    sqft: 1603,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/929771/web/1259-everall-street-white-rock-south-surrey-white-rock-01.jpg?timestamp=1727897467",
    beds: 2, baths: 2, fullBaths: 2, halfBaths: 0,
    mls: "R3130100", type: "House", lotSize: "4,200 sqft", frontage: "42.00 ft",
    taxes: "$6,100.00", parking: "Garage Single", view: "Ocean panoramic",
    basement: "None", storeys: 2, yearBuilt: 2010, style: "Contemporary",
    pricePerSqft: "$1,279",
    description: "Breathtaking panoramic ocean views from this stunning White Rock home. Perched high above the city with sweeping vistas of Semiahmoo Bay, the San Juan Islands, and Mount Baker. A rare find — ocean views at this price in White Rock."
  },
  {
    id: 34,
    address: "16379 28 Avenue",
    area: "Grandview Surrey",
    price: "$5,800,000",
    sqft: 8409,
    tags: ["MOUNTAIN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/916543/web/16379-28-avenue-grandview-surrey-south-surrey-white-rock-01.jpg?timestamp=1722970164",
    beds: 7, baths: 8, fullBaths: 7, halfBaths: 1,
    mls: "R3133400", type: "House", lotSize: "17,400 sqft", frontage: "110.00 ft",
    taxes: "$18,100.00", parking: "Garage Triple, Additional Parking", view: "Mountain panoramic",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2022, style: "Contemporary",
    pricePerSqft: "$690",
    description: "Grand estate in Grandview Surrey with spectacular mountain views. No detail was spared in this custom build — from the grand 22ft foyer to the chef's kitchen, indoor pool, home theatre, and expansive covered outdoor living area."
  },
  {
    id: 35,
    address: "3083 Semiahmoo Trail",
    area: "Elgin Chantrell, Surrey",
    price: "$5,918,000",
    sqft: 6046,
    tags: ["ACREAGE"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/905996/web/3083-semiahmoo-trail-elgin-chantrell-south-surrey-white-rock-01.jpg?timestamp=1718840043",
    beds: 6, baths: 6, fullBaths: 5, halfBaths: 1,
    mls: "R3136700", type: "House", lotSize: "43,560 sqft", frontage: "195.00 ft",
    taxes: "$17,400.00", parking: "Garage Triple, Additional Parking", view: "Garden and trees",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2015, style: "Traditional",
    pricePerSqft: "$979",
    description: "Magnificent estate on a full acre on the prestigious Semiahmoo Trail. This distinguished home exudes elegance with its grand proportions, gourmet kitchen, main floor master, home theatre, and meticulously landscaped grounds with pool and spa."
  },
  {
    id: 36,
    address: "1351 Kerfoot Road",
    area: "White Rock",
    price: "$4,188,000",
    sqft: 6026,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/903488/web/1351-kerfoot-road-white-rock-south-surrey-white-rock-01.jpg?timestamp=1718067066",
    beds: 5, baths: 5, fullBaths: 4, halfBaths: 1,
    mls: "R3140000", type: "House", lotSize: "11,800 sqft", frontage: "80.00 ft",
    taxes: "$13,500.00", parking: "Garage Double, Additional", view: "Ocean and mountain",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2018, style: "Contemporary",
    pricePerSqft: "$695",
    description: "Commanding ocean views from this stunning White Rock contemporary. Situated on a generous 11,800 sqft lot, this architecturally designed home features panoramic views from all main living areas, a chef's kitchen, and a spectacular view deck."
  },
  {
    id: 37,
    address: "14336 Marine Drive",
    area: "White Rock",
    price: "$4,498,000",
    sqft: 3967,
    tags: ["WATERFRONT"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/891860/web/14336-marine-drive-white-rock-south-surrey-white-rock-01.jpg?timestamp=1714167336",
    beds: 4, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R3143300", type: "House", lotSize: "7,200 sqft", frontage: "60.00 ft",
    taxes: "$13,900.00", parking: "Garage Single, Open", view: "Ocean, direct waterfront",
    basement: "None", storeys: 2, yearBuilt: 2005, style: "West Coast",
    pricePerSqft: "$1,134",
    description: "Coveted Marine Drive waterfront property with direct beach access. Wake up to the sound of the ocean in this beautifully maintained home with sweeping views across Semiahmoo Bay. A rare opportunity to own one of White Rock's prized waterfront addresses."
  },
  {
    id: 38,
    address: "14038 27A Avenue",
    area: "Sunnyside Park, Surrey",
    price: "$6,899,000",
    sqft: 10312,
    tags: ["ACREAGE"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/888940/web/14038-27a-avenue-sunnyside-park-surrey-south-surrey-white-rock-01.jpg?timestamp=1713231584",
    beds: 7, baths: 8, fullBaths: 7, halfBaths: 1,
    mls: "R3146600", type: "House", lotSize: "43,560 sqft", frontage: "185.00 ft",
    taxes: "$20,600.00", parking: "Garage Quad, Additional Parking", view: "Garden, pastoral",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2019, style: "Contemporary",
    pricePerSqft: "$669",
    description: "One of Sunnyside Park's finest estates, set on a breathtaking one-acre lot. This custom-built masterpiece features a grand open layout, show-stopping chef's kitchen, indoor pool, wine cellar, home theatre, and a resort-worthy outdoor living space."
  },
  {
    id: 39,
    address: "2165 123 Street",
    area: "Crescent Beach / Ocean Park",
    price: "$27,999,999",
    sqft: 12480,
    tags: ["WATERFRONT"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/400972/web/2165-123-st-0024.jpg?timestamp=1685470396",
    beds: 8, baths: 10, fullBaths: 8, halfBaths: 2,
    mls: "R3149900", type: "House", lotSize: "32,670 sqft", frontage: "175.00 ft",
    taxes: "$62,000.00", parking: "Garage Quad, Additional Parking, Coach House", view: "Ocean, direct waterfront",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2021, style: "Ultra-Luxury Contemporary",
    pricePerSqft: "$2,243",
    description: "The crown jewel of Crescent Beach. This extraordinary waterfront trophy estate is simply unrivalled in the Lower Mainland. A staggering 12,480 sqft residence on 3/4 of an acre of direct ocean frontage — with private dock, infinity pool, and every conceivable luxury."
  },
  {
    id: 40,
    address: "20340 2 Avenue",
    area: "Campbell Valley, Langley",
    price: "Upon Request",
    sqft: 9804,
    tags: ["ACREAGE"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/300664/web/20340-2-avenue-campbell-valley-langley-02.jpg?timestamp=1634068492",
    beds: 6, baths: 7, fullBaths: 6, halfBaths: 1,
    mls: "R3153200", type: "House", lotSize: "217,800 sqft", frontage: "N/A",
    taxes: "Upon Request", parking: "Garage Triple, Additional Parking, Barn", view: "Pastoral and mountain",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2017, style: "Country Estate",
    pricePerSqft: "N/A",
    description: "An extraordinary 5-acre country estate in prestigious Campbell Valley, Langley. This magnificent property offers the ultimate rural luxury lifestyle — a grand custom home, equestrian facilities, expansive grounds, and complete privacy just minutes from urban amenities."
  },
  {
    id: 41,
    address: "13289 12B Avenue",
    area: "Crescent Bch Ocean Pk., South Surrey White Rock",
    price: "$3,688,000",
    sqft: 3509,
    tags: ["OCEAN VIEW"],
    img: "https://dyhx7is8pu014.cloudfront.net/www.team-mcknight.com/homes/1074523/web/13289-12b-avenue-crescent-bch-ocean-pk-south-surrey-white-rock-01.jpg",
    beds: 5, baths: 4, fullBaths: 3, halfBaths: 1,
    mls: "R2987523", type: "House", lotSize: "N/A", frontage: "N/A",
    taxes: "Upon Request", parking: "Garage Double", view: "Ocean view",
    basement: "Full, Finished", storeys: 2, yearBuilt: 2018, style: "Contemporary",
    pricePerSqft: "$746",
    description: "A stunning ocean view home in the sought-after Crescent Beach/Ocean Park community of South Surrey. This beautifully crafted residence offers panoramic views, an open-concept living space, gourmet kitchen, and resort-style outdoor entertaining areas — all just minutes from the beach."
  },
  {
    id: 42,
    address: "2289 131A Street",
    area: "South Surrey White Rock",
    price: "$2,338,000",
    sqft: 0,
    tags: [],
    img: "2899.png",
    beds: 4, baths: 3, fullBaths: 3, halfBaths: 0,
    mls: "", type: "House", lotSize: "N/A", frontage: "N/A",
    taxes: "Upon Request", parking: "Garage Double", view: "",
    basement: "Full, Finished", storeys: 2, yearBuilt: 0, style: "Contemporary",
    pricePerSqft: "",
    description: "A beautifully appointed home in the prestigious South Surrey community. Features an elegant open-concept layout, high-end finishes throughout, and a private backyard — ideally located close to top schools, parks, and shopping."
  },
  {
    id: 43,
    address: "15460 36A Avenue",
    area: "South Surrey White Rock",
    price: "$1,889,000",
    sqft: 0,
    tags: [],
    img: "15460.png",
    beds: 4, baths: 3, fullBaths: 3, halfBaths: 0,
    mls: "", type: "House", lotSize: "N/A", frontage: "N/A",
    taxes: "Upon Request", parking: "Garage Double", view: "",
    basement: "Full, Finished", storeys: 2, yearBuilt: 0, style: "Contemporary",
    pricePerSqft: "",
    description: "A stunning property in South Surrey offering a perfect blend of comfort and luxury. Spacious interiors, quality craftsmanship, and a prime location close to amenities, parks, and top-rated schools."
  }
];
